### ISSUE TITLE
How to generate InfoPlist.strings?

### ISSUE THREAD

**Issue by RomanPodymov** [AckeeCZ/ACKLocalization#31]
Hello.
Thank you for **ACKLocalization**.
As I understand with **ACKLocalization** I can only generate **Localizable.strings**. But what about **InfoPlist.strings**?

**Comment by olejnjak** [comment]
Hi 👋 it is mentioned in the [README](https://github.com/AckeeCZ/ACKLocalization#spreadsheet-structure)

You want to generate InfoPlist.strings use in your spreadsheet key `plist.InfoPlist.<key>` this will generate InfoPlist.strings alongside generated files.

Otherwise you can use another sheet tab or sheet and invoke ACKLocalization once more.

**Comment by RomanPodymov** [comment]
Hello @olejnjak 
Thanks for the clarification.
